# Generated by Django 5.0.1 on 2024-02-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Eligibility', models.TextField()),
                ('Eligible', models.TextField()),
                ('Contacts_offline_applications', models.URLField()),
                ('Special_Categories', models.TextField()),
                ('Scholarship_Fellowship', models.TextField()),
                ('Level', models.TextField()),
                ('State', models.TextField(default='Unknown', max_length=255)),
                ('Application_Period', models.TextField()),
                ('Links_online_application', models.TextField()),
            ],
        ),
    ]
